CFLAGS=-fopenmp -Wall -lm

all:
	gcc -o 1_hello_world 1_hello_world.c $(CFLAGS)
	gcc -o 2_matrix_multiplication 2_matrix_multiplication.c $(CFLAGS)
	gcc -o 3_eratosthene 3_eratosthene.c $(CFLAGS)
	gcc -o 4_charCount 4_charCount.c $(CFLAGS)
